schema = 3

[mod]
  [mod."github.com/alecthomas/template"]
    version = "v0.0.0-20160405071501-a0175ee3bccc"
    hash = "sha256-sjuHfqM34m9uL7muq2JwZsj2HPRNuYSdZ2FuI+DeT2I="
  [mod."github.com/alecthomas/units"]
    version = "v0.0.0-20151022065526-2efee857e7cf"
    hash = "sha256-dJWY/6oZSgkTQIdm+P5/lR/gWHZLXZZozUunhUNaxcg="
  [mod."github.com/apex/log"]
    version = "v1.1.1"
    hash = "sha256-VrNGobBoe5Axdu4lTNa7JM1FPelOLOFNNB07FjeThMk="
  [mod."github.com/aphistic/golf"]
    version = "v0.0.0-20180712155816-02c07f170c5a"
    hash = "sha256-w5zOLFOYqCNnDii4kao6MmBYxBuyMEvywjyJtdJSPeI="
  [mod."github.com/aphistic/sweet"]
    version = "v0.2.0"
    hash = "sha256-g/Bn3aaTIUYZ3stwAtX4Om7XicAbdC8s9su47p7CZK0="
  [mod."github.com/aws/aws-sdk-go"]
    version = "v1.20.6"
    hash = "sha256-ej9kTOr3yBIdbb735T51DRWHWF7pSodBAPCo0lFhLM0="
  [mod."github.com/aybabtme/rgbterm"]
    version = "v0.0.0-20170906152045-cc83f3b3ce59"
    hash = "sha256-GBRMU19dCef6+m4U6u7njGbUw6Iud7tnRCYRY+XudXM="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.0"
    hash = "sha256-Pf2w+tFkeW9J18AR6lZWdu7n8CxfRTW8iL2UZ1z4NsQ="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/fatih/color"]
    version = "v1.7.0"
    hash = "sha256-4In7ef7it7d+6oGUJ3pkD0V+lsL40hVtYdy2KD2ovn0="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.4.7"
    hash = "sha256-j/Ts92oXa3k1MFU7Yd8/AqafRTsFn7V2pDKCyDJLah8="
  [mod."github.com/go-kit/kit"]
    version = "v0.8.0"
    hash = "sha256-EWRJSQWDNhbzr9EvEzFg76Kn7G/2VBgsiAADHZvqU4s="
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.4.0"
    hash = "sha256-qX6aMMNTmN+D7LtQLZxW/LAKxRpze4vO77F2EQLrVRs="
  [mod."github.com/go-stack/stack"]
    version = "v1.8.0"
    hash = "sha256-26RlTEcAkbewMUtmirKrDGQ1WJlNousp69v7HMopYnI="
  [mod."github.com/gogo/protobuf"]
    version = "v1.1.1"
    hash = "sha256-AmlVpKOrFGBUTVR7J5grNUlVJ3hiJcHY8nq+jDRV26s="
  [mod."github.com/golang/protobuf"]
    version = "v1.3.1"
    hash = "sha256-eLr0yrIO2wTtL+LvFKM3styaQSPnZQYSpaDjajBQT7Q="
  [mod."github.com/google/uuid"]
    version = "v1.1.1"
    hash = "sha256-66PXC/RCPUyhS9PhkIPQFR3tbM2zZYDNPGXN7JJj3UE="
  [mod."github.com/hpcloud/tail"]
    version = "v1.0.0"
    hash = "sha256-7ByBr/RcOwIsGPCiCUpfNwUSvU18QAY+HMnCJr8uU1w="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.0.0-20180206201540-c2b33e8439af"
    hash = "sha256-n5VGqJtkJxPhD3E8mWbUNjhT0dQfOj1m97l51Js/3OQ="
  [mod."github.com/jpillora/backoff"]
    version = "v0.0.0-20180909062703-3050d21c67d7"
    hash = "sha256-u8vErRztp16De3Ursrp6REISOKgHQ8d05K+8nnq7qts="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.6"
    hash = "sha256-AQvfLt0tm22yphiZPktC7Y+YZVzq0Jjd8hQa8MSnyJc="
  [mod."github.com/julienschmidt/httprouter"]
    version = "v1.2.0"
    hash = "sha256-xhj9PYKNIfQ/CQb8/3O3OtBmiIAJYtiL23cTnRj1C80="
  [mod."github.com/konsorten/go-windows-terminal-sequences"]
    version = "v1.0.1"
    hash = "sha256-Nwp+Cza9dIu3ogVGip6wyOjWwwaq+2hU3eYIe4R7kNE="
  [mod."github.com/kr/logfmt"]
    version = "v0.0.0-20140226030751-b84e30acd515"
    hash = "sha256-CePQbqWGtS8qP/Av9pkLiqZwH6RaZQff/s1l+1//jQo="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.2"
    hash = "sha256-dkRbC2vKUIMndsFfO2IuFhGHPXU89ZTasXP+ykeVIhQ="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.8"
    hash = "sha256-EMWTTlMvuXlCpExYw88VJYDwULXx+Ckuqrw4I3OADmc="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.1"
    hash = "sha256-ystDNStxR90j4CK+AMcEQ5oyYFRgWoGdvWlS0XQMDLQ="
  [mod."github.com/mgutz/ansi"]
    version = "v0.0.0-20170206155736-9520e82c474b"
    hash = "sha256-MnBed2XD418sSMjuE2hVrqWWvCQYuMDNOEZIEoYQfwE="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.1"
    hash = "sha256-5D1HGVBc/REwPVdlPYcXsbZM80OIh7V5uiyKAbMA5qo="
  [mod."github.com/mwitkow/go-conntrack"]
    version = "v0.0.0-20161129095857-cc309e4a2223"
    hash = "sha256-rgZ2fm0Vi04xGDhkeFPDSZ+KPKi0a/5rerjOdea1eVk="
  [mod."github.com/onsi/ginkgo"]
    version = "v1.6.0"
    hash = "sha256-yTez+VQSBEhRHTfpHZrj1ay69iGP5r7pnSjSzic/3Vc="
  [mod."github.com/onsi/gomega"]
    version = "v1.5.0"
    hash = "sha256-KXt9BlwrWnNo4dSaO1sqfhe6SOBa7EEqCGS/pick8dg="
  [mod."github.com/pkg/errors"]
    version = "v0.8.1"
    hash = "sha256-oe3iddfoLRwpC3ki5fifHf2ZFprtg99iNak50shiuDw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.0.0"
    hash = "sha256-JtIVmlm/CxIRmzM2k8kZ4hM9fo1/Wxt7+wfLEX2zA7g="
  [mod."github.com/prometheus/client_model"]
    version = "v0.0.0-20190129233127-fd36f4220a90"
    hash = "sha256-RSktK1tyVTRf1QRBpzMYchQOrBCMJPqoozSYMcVpRa8="
  [mod."github.com/prometheus/common"]
    version = "v0.4.1"
    hash = "sha256-2iTkFDqAkef1muXgwxPCHV3/x7wxb9cwDJ+uyZrUxGk="
  [mod."github.com/prometheus/procfs"]
    version = "v0.0.2"
    hash = "sha256-hhJ2rT0+wWl2+ZBt7s0WoXshH8ro/CYjjamp6sHzG74="
  [mod."github.com/rogpeppe/fastuuid"]
    version = "v1.1.0"
    hash = "sha256-7wdW8qBm74Hs/grNxKQC/wcpvGhzJBkFaHV8329xkco="
  [mod."github.com/sergi/go-diff"]
    version = "v1.0.0"
    hash = "sha256-I8rbJFKm44u/wS/gz+2yX9882xXcBdb9mKEKq5OoJRU="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.2.0"
    hash = "sha256-70UZATwvZ5xL0pNWoq2UuiL0SG9U/W1/a0jTJToZw2Q="
  [mod."github.com/smartystreets/assertions"]
    version = "v1.0.0"
    hash = "sha256-sI2UUdq1+H+rcLysKDXDeaXi1Pz+zq28d/o/mV0c2wE="
  [mod."github.com/smartystreets/go-aws-auth"]
    version = "v0.0.0-20180515143844-0c1422d1fdb9"
    hash = "sha256-bSQq50eiVJH4iTIPbu722HEOuGseRZd+iNG9Yd9tLk8="
  [mod."github.com/smartystreets/gunit"]
    version = "v1.0.0"
    hash = "sha256-JsN09QCLnEWLv9EcJPqI0HGtdeR67QClHk4qv5EQnW8="
  [mod."github.com/stretchr/objx"]
    version = "v0.1.1"
    hash = "sha256-HdGVZCuy7VprC5W9UxGbDmXqsKADMjpEDht7ilGVLco="
  [mod."github.com/stretchr/testify"]
    version = "v1.3.0"
    hash = "sha256-+mSebBNccNcxbY462iKTNTWmd5ZuUkUqFebccn3EtIA="
  [mod."github.com/tj/assert"]
    version = "v0.0.0-20171129193455-018094318fb0"
    hash = "sha256-44u4f/pbA2wSMrrbLKgPDdS7Hb8KjNpAaBOW++NRM5Y="
  [mod."github.com/tj/go-elastic"]
    version = "v0.0.0-20171221160941-36157cbbebc2"
    hash = "sha256-yUzMiTLHbmT9BGntSL9fe/hGuN6VWHK+3Hi7BQnbJOU="
  [mod."github.com/tj/go-kinesis"]
    version = "v0.0.0-20171128231115-08b17f58cb1b"
    hash = "sha256-pNEKM4JX7n23AH/TT40fh2vnkRllC2aZYBBmI8s1DIE="
  [mod."github.com/tj/go-spin"]
    version = "v1.1.0"
    hash = "sha256-mpjqL1+Ex49p5dKzYOsuJWvQeBwqxxa85rfUkNIxuYc="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20190426145343-a29dc8fdc734"
    hash = "sha256-NzAYTSaYuTWn7Dn4fIEUVNdiucRhThUY90BjBYmUwB0="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20190620200207-3b0461eec859"
    hash = "sha256-lVNbp7zOBVbvzA1fFR4SkUskYfAMt2eILoWuDgk0oS4="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20181221193216-37e7f081c4d4"
    hash = "sha256-FUpv9bmGLDEjCxXdvR0CRDqOKRY0xrHRPzOsyQyvYK0="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20190412213103-97732733099d"
    hash = "sha256-DLQm3nm2Cp7lvX0PXx1OXKCme20QkonBtd4NMgOm4MA="
  [mod."golang.org/x/text"]
    version = "v0.3.0"
    hash = "sha256-0FFbaxF1ZuAQF3sCcA85e8MO6prFeHint36inija4NY="
  [mod."gopkg.in/alecthomas/kingpin.v2"]
    version = "v2.2.6"
    hash = "sha256-uViE2kPj7tMrGYVjjdLOl2jFDmmu+3P7GvnZBse2zVY="
  [mod."gopkg.in/check.v1"]
    version = "v0.0.0-20161208181325-20d25e280405"
    hash = "sha256-1w5mgYaZUC52uzDnpXXVqle/9AVkH4WePSrQFOVANUw="
  [mod."gopkg.in/fsnotify.v1"]
    version = "v1.4.7"
    hash = "sha256-j/Ts92oXa3k1MFU7Yd8/AqafRTsFn7V2pDKCyDJLah8="
  [mod."gopkg.in/tomb.v1"]
    version = "v1.0.0-20141024135613-dd632973f1e7"
    hash = "sha256-W/4wBAvuaBFHhowB67SZZfXCRDp5tzbYG4vo81TAFdM="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.2.1"
    hash = "sha256-QY+DRctY7JryX+Hwtx2p1ThfmK9Zr6OZpu2JS4XOkjc="
